name: Build, Analyze, and Deploy .NET 8 to GCP

on:
  push:
    branches:
      - sonar

env:
  PROJECT_NAME: matrerial
  GCP_PROJECT_ID: devops360-460214
  GCP_REGION: us-central1
  GCR_REPO: web-repo
  IMAGE_NAME: myapp
  SONAR_PROJECT_KEY: material4
  SONAR_HOST_URL: http://35.222.233.219:9000

jobs:
  build-analyze-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Install SonarScanner for .NET
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Begin SonarQube analysis
      run: |
        dotnet-sonarscanner begin /k:"${{ env.SONAR_PROJECT_KEY }}" \
                                 /d:sonar.host.url="${{ env.SONAR_HOST_URL }}" \
                                 /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
    - name: Run tests
      run: dotnet test --no-build --configuration Release

    - name: End SonarQube analysis
      run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.SAKEY }}'

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ env.GCR_REPO }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.GCR_REPO }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest .
        docker push ${{ env.GCR_REPO }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.PROJECT_NAME }} \
          --image ${{ env.GCR_REPO }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest \
          --platform managed \
          --region ${{ env.GCP_REGION }} \
          --project ${{ env.GCP_PROJECT_ID }} \
          --allow-unauthenticated