name: Build, Push Docker Image, and Deploy to GKE

on:
  push:
    branches:
      - main
      - develop
      - release

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET 8 SDK
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore material.sln

      # Build the solution
      - name: Build solution
        run: dotnet build material.sln --configuration Release --no-restore

      # Docker Hub login
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/material:${{ github.ref_name }} .

      # Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/material:${{ github.ref_name }}

      # Install gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Configure kubectl to use GKE
      - name: Get GKE credentials
        run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      # Deploy to GKE
      - name: Deploy to GKE
        run: |
          kubectl set image deployment/material-deployment material=${{ secrets.DOCKER_USERNAME }}/material:${{ github.ref_name }}
          kubectl rollout status deployment/material-deployment
